import numpy as np
from scipy import interpolate

# This module provides functions for reading and writing XSF files.
# The functions are used for reading and writing XSF files and for converting between Cartesian and fractional coordinates.


def get_params_from_xsf(file_name):
    """
    Extract parameters from an XSF file generated by pp.x.

    Parameters
    ----------
    file_name : str
        The name of the XSF file to be read.

    Returns
    -------
    dict
        A dictionary containing the extracted parameters.
    """
    print(f'XSF file name = {file_name}')
    lines_iter = iter(open(file_name, 'r').readlines())
    for line in lines_iter:
        if 'PRIMVEC' in line:
            break
    # Read primitive vectors
    prim_a_vec = [float(s) for s in next(lines_iter).split()]
    prim_b_vec = [float(s) for s in next(lines_iter).split()]
    prim_c_vec = [float(s) for s in next(lines_iter).split()]
    next(lines_iter)
    # Read number of atoms
    natom = int(next(lines_iter).split()[0])
    # Read atomic coordinates
    prim_coord = [[] for i in range(natom)]
    for i in range(natom):
        [prim_coord[i].append(str(s)) for s in next(lines_iter).split()]
    [next(lines_iter) for i in range(3)]
    # Read grid information
    grid_info = [int(s) for s in next(lines_iter).split()]
    pos_org = [float(s) for s in next(lines_iter).split()]
    a_vec = [float(s) for s in next(lines_iter).split()]
    b_vec = [float(s) for s in next(lines_iter).split()]
    c_vec = [float(s) for s in next(lines_iter).split()]
    # Read grid data
    vals_str = ''
    while True:
        line = next(lines_iter)
        if 'END_DATAGRID_3D' in line:
            break
        vals_str += line
    data = np.array([float(s) for s in vals_str.split()])
    # Store parameters in a dictionary
    params = {
        'xsf_name': file_name,
        'prim_vec': [prim_a_vec, prim_b_vec, prim_c_vec],
        'num_atom': natom,
        'prim_coord': prim_coord,
        'grid_info': grid_info,
        'pos_org': pos_org,
        'span_vec': [a_vec, b_vec, c_vec],
        'grid_data': data,
    }
    return params

def output_xsf(params):
    """
    Write parameters to an XSF file.

    Parameters
    ----------
    params : dict
        A dictionary containing the parameters to be written to the XSF file.
    """
    xsf = 'CRYSTAL\nPRIMVEC\n'
    # Write primitive vectors
    for vec in params['prim_vec']:
        xsf += '{0[0]:>15.9f}{0[1]:>15.9f}{0[2]:>15.9f}\n'.format(vec)
    xsf += 'PRIMCOORD\n'
    xsf += '{0:>5d}  1\n'.format(params["num_atom"])
    # Write atomic coordinates
    for atoms in params['prim_coord']:
        xsf += '{0[0]:>2s} {0[1]:>15s} {0[2]:>15s} {0[3]:>15s}\n'.format(atoms)
    xsf += 'BEGIN_BLOCK_DATAGRID_3D\n3D_PWSCF\nDATAGRID_3D_UNKNOWN\n'
    xsf += '{0[0]:>5d}{0[1]:>5d}{0[2]:>5d}\n'.format(params['grid_info'])
    xsf += '{0[0]:>10.6f}{0[1]:>10.6f}{0[2]:>10.6f}\n'.format(params['pos_org'])
    # Write spanning vectors
    for vec in params['span_vec']:
        xsf += '{0[0]:>10.6f}{0[1]:>10.6f}{0[2]:>10.6f}\n'.format(vec)
    # Write grid data
    nx, ny, nz = params['grid_info']
    for z in range(nz): 
        for y in range(ny):
            start = z * nx * ny + y * nx
            end = start + nx
            for value in params['grid_data'][start:end:1]:
                xsf += '{0:>14.6E}'.format(value)
            xsf += '\n'
        xsf += '\n'
    xsf += 'END_DATAGRID_3D\nEND_BLOCK_DATAGRID_3D'
    open(params['xsf_name'], 'w').write(xsf)

def get_data_for_new_grid(data, grid_info, grid_info_new, shift_grid=False):
    """
    Interpolate 3D grid data to generate new grid data.

    Parameters
    ----------
    data : np.ndarray
        Original grid data.
    grid_info : list of int
        Dimensions of the original grid.
    grid_info_new : list of int
        Dimensions of the new grid.
    shift_grid : bool, optional
        Whether to shift the new grid by half a grid spacing (default is False).

    Returns
    -------
    np.ndarray
        Interpolated grid data.
    """
    import itertools

    from scipy import interpolate

    # Get original grid data
    nx0, ny0, nz0 = grid_info
    data_reshape = np.zeros((nx0, ny0, nz0))
    for i, j, k in itertools.product(range(nx0), range(ny0), range(nz0)):
        data_reshape[i, j, k] = data[(i % nx0) + (j % ny0) * nx0 + (k % nz0) * nx0 * ny0]
    # Preparation for linear interpolation
    x0, y0, z0 = [np.linspace(0, 1, n, endpoint=False) for n in grid_info]
    f = interpolate.RegularGridInterpolator((x0, y0, z0), data_reshape)
    if shift_grid:
        x1, y1, z1 = [np.linspace(0, 1, n, endpoint=False) + 1.0 / (2 * n) for n in grid_info_new]
    else:
        x1, y1, z1 = [np.linspace(0, 1, n, endpoint=False) for n in grid_info_new]
    # Get new grid data
    nx1, ny1, nz1 = grid_info_new
    data_new = np.zeros((nx1, ny1, nz1))
    for i, j, k in itertools.product(range(nx1), range(ny1), range(nz1)):
        data_new[i, j, k] = f((x1[i], y1[j], z1[k]))
    return data_new

def get_data_for_new_grid_npbc(data, grid_info, grid_info_new, shift_grid=True): 
    """
    Interpolate 3D grid data to generate new grid data without periodic boundary conditions.

    Parameters
    ----------
    data : np.ndarray
        Original grid data.
    grid_info : list of int
        Dimensions of the original grid.
    grid_info_new : list of int
        Dimensions of the new grid.
    shift_grid : bool, optional
        Whether to shift the new grid by half a grid spacing (default is True).

    Returns
    -------
    np.ndarray
        Interpolated grid data.
    """
    from scipy import interpolate
    [nx, ny, nz] = grid_info
    i, j, k = np.meshgrid(range(nx), range(ny), range(nz), indexing='ij')
    indices = (i % nx) + (j % ny) * nx + (k % nz) * nx * ny
    data_reshape = data[indices]

    x0, y0, z0 = [np.linspace(0, 1, n, endpoint=False) for n in grid_info]
    f = interpolate.RegularGridInterpolator((x0, y0, z0), data_reshape, bounds_error=False, fill_value=None)
    if shift_grid:
        x1, y1, z1 = [np.linspace(0, 1, n, endpoint=False) + 1.0 / (2 * n) for n in grid_info_new]
    else:
        x1, y1, z1 = [np.linspace(0, 1, n, endpoint=False) for n in grid_info_new]
    mesh_new = np.array(np.meshgrid(x1, y1, z1, indexing='ij')) 
    points_new = mesh_new.reshape(3, -1).T    
    data_new = f(points_new).reshape(grid_info_new)
    return data_new

def get_data_for_new_grid(data, grid_info, grid_info_new):
    """
    Interpolate 3D grid data to generate new grid data.

    Parameters
    ----------
    data : np.ndarray
        Original grid data.
    grid_info : list of int
        Dimensions of the original grid.
    grid_info_new : list of int
        Dimensions of the new grid.

    Returns
    -------
    np.ndarray
        Interpolated grid data.
    """
    from scipy import interpolate
    nx, ny, nz = grid_info
    i, j, k = np.meshgrid(range(nx), range(ny), range(nz), indexing='ij')
    indices = (i % nx) + (j % ny) * nx + (k % nz) * nx * ny
    data_reshape = data[indices]

    x0, y0, z0 = [np.linspace(0, 1, n, endpoint=False) for n in grid_info]
    f = interpolate.RegularGridInterpolator((x0, y0, z0), data_reshape)

    m1, m2, m3 = grid_info_new
    flag = False
    x1 = np.linspace(0, 1, m1, endpoint=flag)
    y1 = np.linspace(0, 1, m2, endpoint=flag)
    z1 = np.linspace(0, 1, m3, endpoint=flag)
    mesh_new = np.array(list(np.meshgrid(x1, y1, z1, indexing='ij')))
    points_new = mesh_new.reshape(3, -1).T
    data_new = f(points_new).reshape(m1, m2, m3)
    return data_new

def grid2pos(grid_coords, grid_vec, spanning_vec, rorg):
    """
    Convert grid coordinates to Cartesian coordinates.

    Parameters
    ----------
    grid_coords : np.ndarray
        Grid coordinates.
    grid_vec : np.ndarray
        Grid vector dimensions.
    spanning_vec : np.ndarray
        Spanning vectors.
    rorg : np.ndarray
        Origin of the positions.

    Returns
    -------
    np.ndarray
        Cartesian coordinates.
    """
    dspanning_vec = spanning_vec / (grid_vec - np.array([1, 1, 1]))
    return np.dot(grid_coords, dspanning_vec) + rorg

def get_values(coords, grid_vec, data):
    """
    Get interpolated values at specified coordinates.

    Parameters
    ----------
    coords : np.ndarray
        Coordinates at which to interpolate values.
    grid_vec : np.ndarray
        Grid vector dimensions.
    data : np.ndarray
        Grid data.

    Returns
    -------
    np.ndarray
        Interpolated values.
    """
    nx, ny, nz = grid_vec
    x0 = np.linspace(0, 1, nx + 1)
    y0 = np.linspace(0, 1, ny + 1)
    z0 = np.linspace(0, 1, nz + 1)
    data_reshape = np.pad(data, ((0, 1), (0, 1), (0, 1)), mode='wrap')
    f = interpolate.RegularGridInterpolator((x0, y0, z0), data_reshape)
    mesh_new = np.array(np.meshgrid(np.arange(nx), np.arange(ny), np.arange(nz), indexing='ij'))
    points_new = coords[mesh_new[0], mesh_new[1], mesh_new[2]] / grid_vec
    points_new_reshaped = points_new.reshape(-1, 3)
    values_reshaped = f(points_new_reshaped)
    values = values_reshaped.reshape(nx, ny, nz)
    return values

def get_values_new(points, grid_vec, data):
    """
    Get interpolated values at specified points.

    Parameters
    ----------
    points : np.ndarray
        Points at which to interpolate values.
    grid_vec : np.ndarray
        Grid vector dimensions.
    data : np.ndarray
        Grid data.

    Returns
    -------
    np.ndarray
        Interpolated values.
    """
    n1, n2, n3 = grid_vec 
    i, j, k = np.meshgrid(range(n1), range(n2), range(n3), indexing='ij')
    indices = (i % n1) + (j % n2) * n1 + (k % n3) * n1 * n2
    data_ir = data[indices]

    l = np.linspace(0, 1, n1 + 1)
    m = np.linspace(0, 1, n2 + 1)
    n = np.linspace(0, 1, n3 + 1)
    data_full = np.zeros((n1 + 1, n2 + 1, n3 + 1))
    for i in range(n1):
        for j in range(n2):
            for k in range(n3):
                data_full[i, j, k] = data_ir[i, j, k]
    data_full[-1, :, :] = data_full[0, :, :]
    data_full[:, -1, :] = data_full[:, 0, :]
    data_full[:, :, -1] = data_full[:, :, 0]

    f = interpolate.RegularGridInterpolator((l, m, n), data_full)
    values = f(points)
    return values

if __name__ == '__main__':
    xsf_file = '../pbe_spn_rrkjus/pp_gamma_0.6/A0_B003.wfc.xsf'
    params = get_params_from_xsf(xsf_file)
    grid_new = [32, 32, 32]
    data_new = get_data_for_new_grid(params['grid_data'], params['grid_info'], grid_new, shift_grid=True)
    np.save('image', data_new)
